spring.application.name: spring-boot-config

my:
  greetings: Hello World
  list:
    values: One, Two, Three

app:
  name: My App
  description: Welcome to ${app.name}

dbValues: "{connectionString: 'http://____', userName: 'foo', password: 'pass'}"

db:
  connection: "{connectionString: 'http://____', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 8080

management.endpoints.web.exposure.include: "*"

#spring.cloud.config.uri: http://localhost:8888

spring.config.import: configserver:http://localhost:8888


# spring.profiles.active: test
